<?php
require '/app/views/templateDefault.php';
?> 
                <?php
                if (isset($view_editar)) {
                    foreach ($view_editar as $editar) {
                        $editar_id = $editar['id'];
                        $editar_nome = $editar['descricao'];
                        $editar_cientifico = $editar['nome_cientifico'];
                        $editar_autor = $editar['autor'];
                        $editar_ano = $editar['ano'];

                        /* Botão */
                        $button = 'editar';
                        $button_name = 'ATUALIZAR';
                        $action = '/id/' . $editar_id;
                    }
                } else {
                    $editar_id = '';
                    $editar_nome = '';
                    $editar_cientifico = '';
                    $editar_autor = '';
                    $editar_ano = '';

                    /* Botão */
                    $action = '';
                    $button = 'cadastrar';
                    $button_name = 'CADASTRAR';
                }
                ?>
                <div>
                    <div id="cadastro" class="title"><p>Cadastro de &Aacute;rvores</p></div>
                    <div class="form">
                        <form action="/arvore/cadastrarAction<?php echo $action; ?>" method="post">

                            <input id="id" name="id" hidden="" type="text" value="<?php echo $editar_id; ?>">
                            <p>
                                <label for="descricao" class="cell">NOME COMUM:</label>
                            </p>
                            <p>
                                <input id="descricao" name="descricao" size="50" required="required" type="text" value="<?php echo $editar_nome; ?>">
                            </p>
                            <p>
                                <label for="nome_cientifico" class="cell">NOME CIENT&Iacute;FICO:</label>
                            </p>
                            <p>
                                <input id="nome_cientifico" name="nome_cientifico" size="50" required="required" type="text" value="<?php echo $editar_cientifico; ?>">
                            </p>
                            <p>
                                <label for="autor" class="cell">AUTOR:</label>
                            </p>
                            <p>
                                <input id="autor" name="autor" size="50" required="required" type="text" value="<?php echo $editar_autor; ?>">
                            </p>
                            <p>
                                <label for="ano" class="cell">ANO:</label>
                            </p>
                            <p>
                                <input id="ano" name="ano" size="5" required="required" type="text" value="<?php echo $editar_ano; ?>">
                            </p>
                            </tr>
                            </table>

                    </div>
                    <div class="controle">
                        <input type="submit" class="<?php echo $button; ?>Button" value="<?php echo $button_name; ?>">
                        <!--<input type="submit" class="cadastrarButton" value="CADASTRAR">-->
                        <a href="/arvore/cons" class="consultaAllButton">Listar Todos</a>
<!--                        <input type="submit" class="excluirButton" value="EXCLUIR">
                        <input type="submit" class="editarButton" value="EDITAR">-->
                    </div>
                    </form>
                </div>

            </div>

            <div id="footer">
                <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
            </div>
        </div>

        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
