<?php
require TEMPLATE.'templateDefault.php';
?>  
                <?php
                if (isset($view_editar)) {
                    foreach ($view_editar as $editar) {
                        $editar_id = $editar['id'];
                        $editar_nome = $editar['descricao'];
                        $editar_cargo = $editar['cargo'];
                        $editar_email = $editar['email'];
                        $editar_login = $editar['login'];
                        $editar_senha = 'disabled';
                        /* Botão */
                        $button = 'editar';
                        $button_name = 'ATUALIZAR';
                        $action = '/id/' . $editar_id;
                    }
                } else {
                    $editar_id = '';
                    $editar_nome = '';
                    $editar_cargo = '';
                    $editar_email = '';
                    $editar_login = '';
                    $editar_senha = '';
                    /* Botão */
                    $action = '';
                    $button = 'cadastrar';
                    $button_name = 'CADASTRAR';
                }
                ?>
                <div>
                    <div id="cadastro" class="title"><p>Cadastro de Pessoas</p></div>
                    <div class="form">
                        <form action="/pessoas/cadastrarAction<?php echo $action; ?>" method="post">

                            <input id="id" name="id" hidden="" type="text" value="<?php echo $editar_id; ?>">
                            <p>
                                <label for="descricao" class="cell">NOME:</label>
                            </p>
                            <p>                             
                                <input id="descricao" name="descricao" required="required" type="text" value="<?php echo $editar_nome; ?>">
                            </p>
                            <p>
                                <label for="email" class="cell">E-MAIL:</label>
                            </p>
                            <p>                             
                                <input id="email" name="email" required="required" type="email" value="<?php echo $editar_email; ?>">
                            </p>
                            <p>
                                <label for="login" class="cell">LOGIN:</label>
                            </p>
                            <p>                             
                                <input id="login" name="login" required="required" type="text" value="<?php echo $editar_login; ?>">
                            </p>
                            <p>
                                <label for="senha" class="cell">SENHA:</label>
                            </p>
                            <p>                             
                                <input id="senha" name="senha" required="required" type="password" <?php echo $editar_senha ?>>
                            </p>
                            <p>
                                <label class="cell">CARGO:</label>
                            </p>
                            <p> 
                                <select name='cargo'>
                                    <?php foreach ($view_cargo as $cargo) : ?>
                                        <option value="<?php echo $cargo['id']; ?>" <?php if ($cargo['id'] == $editar_cargo) echo "selected"; ?>> <?php echo $cargo['descricao'] ?></option>
                                    <?php endforeach; ?>
                                </select></p></td>
                            </p>
                            </tr>
                            </table>

                    </div>
                    <div class="controle">
                        <input type="submit" class="<?php echo $button; ?>Button" value="<?php echo $button_name; ?>">
                        <!--<input type="submit" class="cadastrarButton" value="CADASTRAR">-->
                        <a href="/pessoas/cons" class="consultaAllButton">Listar Todos</a>
<!--                        <input type="submit" class="excluirButton" value="EXCLUIR">
                        <input type="submit" class="editarButton" value="EDITAR">-->
                    </div>
                    </form>
                </div>

            </div>

            <div id="footer">
                <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
            </div>
        </div>

        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
