<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>        
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <link type="text/css" href="/web-files/style/css/base.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/home.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/op.css" rel="stylesheet" />


        <title>SISTEMA PAPAGAIO VERDADEIRO</title>

    </head>
    <body>
        <div class="container">
            <div class="bar">
                <div id="sisname">
                    Sistema Papagaio Verdadeiro
                </div>
                <div id="user">
                    Usuário: Murilo
                </div>
            </div>
            <div id="header"></div>
            <div id="home"><a href="../index">HOME</a></div>
            <div id="menu">
                <div>
                    <div id="cadastro" class="title"><p>Cadastro de Pessoas</p></div>
                    <div class="form">
                        <form action="cadastrar" method="post">
                            <p>
                                <label for="descricao" class="cell">NOME:</label>
                                <input id="descricao" name="descricao" required="required" type="text" value="">
                            </p>
                            <p>
                                <label class="cell">CARGO:</label>
                                <select name='cargo'>
                                    <?php foreach ($view_cargo as $cargo) : ?>
                                        <option value="<?php echo $cargo['id']; ?>"><?php echo $cargo['descricao'] ?></option>
                                    <?php endforeach; ?>
                                </select></p></td>
                            </p>
                            </tr>
                            </table>

                    </div>
                    <div class="controle">
                        <input type="submit" class="cadastrarButton" value="CADASTRAR">
                        <a href="cons" class="consultaAllButton">Listar Todos</a>
<!--                        <input type="submit" class="excluirButton" value="EXCLUIR">
                        <input type="submit" class="editarButton" value="EDITAR">-->
                    </div>
                    </form>
                </div>

            </div>

            <div id="footer">
                <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
            </div>
        </div>

        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
