<?php ?>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>        
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <link type="text/css" href="/web-files/style/css/base.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/home.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/op.css" rel="stylesheet" />


        <title>SISTEMA PAPAGAIO VERDADEIRO</title>

    </head>
    <body>

        <div class="container">
            <div class="bar">
                <div id="sisname">
                    Sistema Papagaio Verdadeiro
                </div>
                <div id="user">
                    Usuário: Murilo

                </div>
            </div>
            <div id="header"></div>
            <div id="home"><a href="/index">HOME</a></div>
            <div id="menu">
                <div>
                    <div id="consulta" class="title"><p>Consulta de &Aacute;rvores</p></div>
                </div>
                <form action="/arvore/excluirAction" method="post">
                    <div class='consultaDiv'>
                        <table class="tableCons" CELLSPACING = 0>
                            <tr class="titleCons">
                                <td></td>
                                <td>Nome Comum</td>
                                <td>Nome Científico</td>
                                <td>Autor</td>
                                <td>Ano</td>
                                <td></td>
                                <td></td>
                            </tr>
                            <?php foreach ($view_arvore as $arvore): ?>
                                <tr class="dataCons">
                                    <td class="separadorCons""><div class="consultaCheck">
                                            <input type="checkbox" id="del[]" name="del[]" value="<?php echo $arvore['id']; ?>">
                                        </div></td>
                                    <td><?php echo $arvore['descricao']; ?></td>
                                    <td><?php echo $arvore['nome_cientifico']; ?></td>
                                    <td><?php echo $arvore['autor']; ?></td>
                                    <td><?php echo $arvore['ano']; ?></td>
                                    <td class="separadorCons"><a href="/arvore/cad/id/<?php echo $arvore['id']; ?>" class="consultaButton"><img src="/web-files/style/img/visualizar.ico"></a></td>
                                    <td class="separadorCons"><a href="/arvore/cad/id/<?php echo $arvore['id']; ?>" class="consultaButton">EDITAR</a></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>                    
            </div>
            <div class="controle">
                <!--<input type="submit" class="cadastrarButton" value="CADASTRAR">-->
                <input type="submit" class="excluirButton" value="EXCLUIR">
                <a href="/arvore/cad" class="cadastrarNovoButton">Cadastrar Novo</a>
                <!--<input type="submit" class="editarButton" value="EDITAR">-->
            </div>
        </form>
        <div id="footer">
            <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
        </div>
    </div>
</div>

<script>
    $(function() {
    });
</script>
</body>
</html> 
