<?php
require '/app/views/templateDefault.php';
?> 
                <div>
                    <div id="consulta" class="title"><p>Consulta de Ninhos</p></div>
                </div>
                <div class="consultaTop"">
                    <div>DATE1</div>
                    <div>DATE2</div>
                    <div>DATE3</div>
                    <div>DATE4</div>
                </div>
                <div class="consultaLine""><p>dado1</p></div>
                <div class="consultaLine""><p>sadosahisdiiohsadhioasdhio   aohisdhiohsodhosdhoas</p></div>
                <div class="consultaLine""><p>sadosahisdiiohsadhioasdhio   aohisdhiohsodhosdhoas</p></div>
                <div class="consultaLine""><p>sadosahisdiiohsadhioasdhio   aohisdhiohsodhosdhoas</p></div>
            </div>
            <div id="footer">
                <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
            </div>
            </div>
        </div>

        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
