<?php
require '/app/views/templateDefault.php';
?> 
                <div>
                    <div id="consulta" class="title"><p>Consulta de Pessoas</p></div>
                </div>
                <form action="/pessoas/excluirAction" method="post">
                    
                    <div class='consultaDiv'>
                        <table class="tableCons" CELLSPACING = 0>
                            <tr class="titleCons">
                                <td></td>
                                <td>Nome</td>
                                <td>Cargo</td>
                                <td>Email</td>
                                <td>Login</td>
                                <td></td>
                                <td></td>
                            </tr>
                            <?php foreach ($view_pessoas as $pessoas): ?>
                                <tr class="dataCons">
                                    <td class="separadorCons""><div class="consultaCheck">
                                            <input type="checkbox" id="del[]" name="del[]" value="<?php echo $pessoas['id']; ?>">
                                        </div></td>
                                    <td><?php echo $pessoas['nome']; ?></td>
                                    <td><?php echo $pessoas['cargo']; ?></td>
                                    <td><?php echo $pessoas['email']; ?></td>
                                    <td><?php echo $pessoas['login']; ?></td>
                                    <td class="separadorCons"><a href="/pessoas/cad/id/<?php echo $pessoas['id']; ?>" class="consultaButton" title="Detalhes"><img src="/web-files/style/img/visualizar.ico"></a></td>
                                    <td class="separadorCons"><a href="/pessoas/cad/id/<?php echo $pessoas['id']; ?>" class="consultaButton">EDITAR</a></td>
                                </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                    
            </div>
            <div class="controle">
                <!--<input type="submit" class="cadastrarButton" value="CADASTRAR">-->
                <input type="submit" class="excluirButton" value="EXCLUIR">
                <a href="/pessoas/cad" class="cadastrarNovoButton">Cadastrar Novo</a>
                <!--<input type="submit" class="editarButton" value="EDITAR">-->
            </div>
        </form>
        <div id="footer">
            <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
        </div>
    </div>
</div>

<script>
    $(function() {
    });
</script>
</body>
</html> 
