<?php      
require '/app/views/templateDefault.php';
?> 

            <div id="menu">
                <div>
                    <div id="cadastro" class="title"><p>Cadastro</p></div>
                    <div class="navegacao">
                        <?php foreach ($view_cadastros as $cadastro): ?>
                            <a href="<?php echo $cadastro['url'] ?>"><div class="cad">
                                    <div><?php echo $cadastro['descricao']; ?></div>
                                </div></a>

                        <?php endforeach; ?>
                    </div>
                    <div id="consulta" class="title"><p>Consultas</p></div>
                    <div class="navegacao">
                        <?php foreach ($view_consultas as $consulta): ?>
                            <a href="<?php echo $consulta['url'] ?>"><div class="cons">
                                    <div><?php echo $consulta['descricao']; ?></div>
                                </div></a>

                        <?php endforeach; ?>
                    </div>
                    <div id="relatorio" class="title"><p>Relatórios</p></div>
                    <div class="navegacao">
                        <?php foreach ($view_relatorios as $relatorio): ?>
                            <a href="<?php echo $relatorio['url'] ?>"><div class="relat">
                                    <div><?php echo $relatorio['descricao']; ?></div>
                                </div></a>

                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
            <div id="footer">
                <p>Projeto Papagaio Verdadeiro - Glaucia Seixas</p>
            </div>
        </div>

    <script>
        $(function() {
        });
    </script>
</body>
</html>