<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8" >

        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>        
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <link type="text/css" href="/web-files/style/css/base.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/home.css" rel="stylesheet" />


        <title>SISTEMA PAPAGAIO VERDADEIRO</title>

    </head>
    <body>
        <div class="container">
            <div class="bar">
                <div id="sisname">
                    Sistema Papagaio Verdadeiro
                </div>
                <div id="user">
                    Usuário: Murilo
                </div>
            </div>
            <div id="header"></div>
            <div id="menu">
                <div>
                    <div id="cadastro" class="title"><p>Cadastro</p></div>
                    <div class="navegacao">
                    <?php foreach ($view_cadastros as $cadastro): ?>
                            <a href="view/cadastro/NinhoCad"><div class="cad">
                                    <div><?php echo $cadastro['descricao']; ?></div>
                                </div></a>
                       
                    <?php endforeach; ?>
                    </div>
                    <div id="consulta" class="title"><p>Consultas</p></div>
                    <div class="navegacao">
                    <?php foreach ($view_consultas as $consulta): ?>
                            <a href="view/cadastro/NinhoCad"><div class="cons">
                                    <div><?php echo $consulta['descricao']; ?></div>
                                </div></a>
                       
                    <?php endforeach; ?>
                    </div>
                    <div id="relatorio" class="title"><p>Relatórios</p></div>
                    <div class="navegacao">
                    <?php foreach ($view_relatorios as $relatorio): ?>
                            <a href="view/cadastro/NinhoCad"><div class="relat">
                                    <div><?php echo $relatorio['descricao']; ?></div>
                                </div></a>
                       
                    <?php endforeach; ?>
                    </div>
                </div>
            </div>
            </div>
        </div>

        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
