<?php 
 if(isset($view_erro)){
     $erro = '<div class="alertLogin">Login/Senha incorreto!</div>';
 }
 else {
     $erro = '';
 }
?>
﻿<html>
    <head>

        <title>SISTEMA PAPAGAIO VERDADEIRO</title>

        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>        
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

        <link type="text/css" href="/web-files/style/css/base.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/home.css" rel="stylesheet" />
        <link type="text/css" href="/web-files/style/css/op.css" rel="stylesheet" />
    </head>
    <body class="loginBody">
        <div class="loginContent">
            <div class="loginBlock">
                <div class="loginBox">
                    <p>
                        <img src="/web-files/style/img/papagaios.png" width="200px">
                    </p>

                </div>
            </div>
            <form method="POST" action="/index/logar">
            <div class="loginBlock">
                <div class="loginBox">
                    <?php echo $erro; ?>
                    <p>
                        <label for="login" class="cell">Login:</label>
                    </p>
                    <p>
                        <input id="login" name="login" size="20" required="required" type="text" value="">
                    </p>
                    <p>
                        <label for="senha" class="cell">Senha:</label>
                    </p>
                    <p>
                        <input id="senha" name="senha" size="20" required="required" type="password" value="">
                    </p>
                    <div class="controle">
                        <input type="submit" class="loginButton" value="Entrar">
                    </div>
                </div>
                </form>

            </div>
        </div>
        <script>
            $(function() {
            });
        </script>
    </body>
</html> 
